bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

google:
  credentials:
    private-key-id: ${GOOGLE_CREDENTIALS_PRIVATE_KEY_ID}
    token-uri: ${GOOGLE_CREDENTIALS_TOKEN_URI}
    auth-uri: ${GOOGLE_CREDENTIALS_AUTH_URI}
    client-email: ${GOOGLE_CREDENTIALS_CLIENT_EMAIL}
    client-id: ${GOOGLE_CREDENTIALS_CLIENT_ID}
    project-id: ${GOOGLE_CREDENTIALS_PROJECT_ID}
    private-key: ${GOOGLE_CREDENTIALS_PRIVATE_KEY}
    scopes: ${GOOGLE_CREDENTIALS_SCOPES}
