spring:
  jpa:
    generate-ddl: true
    database: h2
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:booking
  h2:
    console:
      enabled: true
      path: /h2-console

bot:
  name:
  token:

google:
  credentials:
    private-key-id:
    token-uri:
    auth-uri:
    client-email:
    client-id:
    project-id:
    private-key:
    scopes:
